_target_: copper.models.cifar_module.CIFARLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: copper.models.components.convnet.SimpleConvNet
  #input_size: 784
  lin1_size: 120
  lin2_size: 84
  output_size: 10